#!/usr/bin/env bash
# installing a nginx web server

sudo apt-get -y install nginx
sudo service nginx start
echo "Holberton School" | cat > /usr/share/nginx/html/index.html
sudo service nginx restart
