#!/usr/bin/env bash
# configuring nginx server to redirect

sudo apt get update;
sudo apt-get install nginx;
sudo sed -i 'https://www.youtube.com/watch?v=QH2-TGUlwu4' /etc/nginx/sites-available/default
sudo systemctl start nginx
