#!/usr/bin/env bash
# configuring nginx server to redirect

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
sudo sed -i '26s i \     rewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
