#!/usr/bin/env bash
# configuring nginx server to redirect

sudo apt get update;
sudo apt-get -y install nginx;
sudo service start nginx
sudo sed -i 'https://www.youtube.com/watch?v=QH2-TGUlwu4' /etc/nginx/sites-available/default
sudo service start nginx
