#!/usr/bin/env bash
# Transferring a file to my server

if [[ $# < 3 ]];
   then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
else
	scp -oStrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
fi