#!/usr/bin/env bash
#if elif else script"
c=1
while ((c <= 10))
do
	if ((c == 4))
	   then
		echo "bad luck"
	elif ((c == 8))
	     then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	((c++))
done
