#!/usr/bin/env bash
# configuring a ubuntu server

cp /etc/hosts ~/hosts.new
sed -i "s/127.0.0.1/127.0.0.2" /etc/hosts ~/hosts.new
cp -f ~/hosts.new /etc/hosts
echo 8.8.8.8    facebook.com | tee -a /etc/hosts
