#!/usr/bin/env bash
# configuring a web server to match another

shellcheck disable=SC2034
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
sudo sed -i '1/^/add_header X-Served-By $HOSTNAME/' /etc/nginx/nginx.conf
sudo service nginx restart
