#!/usr/bin/env bash
# running nginx as user not root


sudo sed -i 's/listen 80 /listen 8080 /g' /etc/nginx/sites-available/default
sudo chown -R nginx /etc/nginx
sudo chmod -R 755 /etc/nginx/nginx.conf
sudo pkill apache2
sudo service nginx start
