#!/usr/bin/env bash
# running nginx as user not root


sudo pkill apache2
sudo sed -i "s/80/8080/" /etc/nginx/sites-available/default
sudo chown -R nginx /etc/nginx
sudo chmod 755 /etc/nginx/nginx.conf
sudo service nginx stop
su nginx -c nginx
sudo service nginx start
