#!/usr/bin/env bash
# running nginx as user not root


sudo sed -i 's/listen 80 /listen 8080 /g' /etc/nginx/sites-available/default
sudo chmod -R 755 /etc/nginx
sudo sed -i "s/:80 /:8080 /g" /etc/nginx/sites-enabled/default
sudo pkill apache2
sudo su -c "service nginx start" nginx
